name: Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 11 21 09 MON'
  workflow_dispatch:

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4
        
      - name: Decir hola
        run: echo "¡Hola! Este es mi primer workflow de GitHub Actions 🎉"
        
      - name: Mostrar los archivos del repositorio
        run: ls -la
